services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/waiterApp

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
